baseURL = "https://nothingness0db.github.io/"
theme = "LoveIt"
defaultContentLanguage = "zh-cn"

# 是否包括中日韩文字
hasCJKLanguage = true

# 多语言设置
[languages]
  [languages.zh-cn]
    weight = 1
    title = "Eira Hazel"
    languageCode = "zh-CN"
    languageName = "简体中文"
    [[languages.zh-cn.menu.main]]
      weight = 1
      identifier = "music"
      pre = "<i class='fas fa-music fa-fw'></i>"
      post = ""
      name = "音乐"
      url = "/music/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 2
      identifier = "posts"
      pre = ""
      post = ""
      name = "文章"
      url = "/posts/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 3
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 4
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 5
      identifier = "github"
      pre = "<i class='fab fa-github fa-fw'></i>"
      post = ""
      name = ""
      url = "https://github.com/nothingness0db"
      title = "GitHub"
    [[languages.zh-cn.menu.main]]
      weight = 6
      identifier = "rss"
      pre = "<i class='fas fa-rss fa-fw'></i>"
      post = ""
      name = ""
      url = "/index.xml"
      title = "RSS"

  [languages.en]
    weight = 2
    title = "Eira Hazel"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "music"
      pre = "<i class='fas fa-music fa-fw'></i>"
      post = ""
      name = "Music"
      url = "/music/"
      title = ""
    [[languages.en.menu.main]]
      weight = 2
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
    [[languages.en.menu.main]]
      weight = 3
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
    [[languages.en.menu.main]]
      weight = 4
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
    [[languages.en.menu.main]]
      weight = 5
      identifier = "github"
      pre = "<i class='fab fa-github fa-fw'></i>"
      post = ""
      name = ""
      url = "https://github.com/nothingness0db"
      title = "GitHub"
    [[languages.en.menu.main]]
      weight = 6
      identifier = "rss"
      pre = "<i class='fas fa-rss fa-fw'></i>"
      post = ""
      name = ""
      url = "/index.xml"
      title = "RSS"

[params]
  # 网站副标题
  [params.header]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # 主题切换模式
    themeChangeMode = "select"
    # 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = ""
      # 标题名称
      name = "Eira Hazel"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # 是否为标题显示打字机动画
      typeit = false

  [params.home]
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      avatarURL = "images/OIP.jpg"
      imageWidth = 360
      imageHeight = 360
      subtitle = "Welcome to Eira's Blog"
      typeit = true
    
    # 主页文章列表
    [params.home.posts]
      enable = true
      paginate = 6
      defaultHiddenFromHomePage = false
  
  # 页面配置
  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = true
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    
  # 社交链接
  [params.social]
    GitHub = "nothingness0db"
    Twitter = "https://x.com/ADsdssd40847"
    Bilibili = "https://space.bilibili.com/495335682"
    RSS = "/index.xml"

# Hugo 解析文档的配置
[markup]
  [markup.highlight]
    noClasses = false

# 输出文件设置
[outputs]
  home = ["HTML", "RSS", "JSON"]

# 多语言地图
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# 多语言菜单
[menu]
  [[menu.main]]
    identifier = "language"
    pre = "<i class='fas fa-language fa-fw'></i>"
    post = ""
    name = ""
    url = "#"
    title = "Language"
    weight = 6
